import test from 'node:test';
import assert from 'node:assert/strict';
const storage = new Map([['farm-forward:setup:v2', '{"paddockSizeHa":12.5,"soilType":"clay"}']]);
globalThis.localStorage = { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value) };
const { appSession } = await import('../src/frontend/state/app-session.js');
const { ensureBaseline } = await import('../src/frontend/services/baseline-client.js');
const a = { latitude: -30.3296154, longitude: 149.7814491, displayName: 'Narrabri NSW 2390' };
const b = { latitude: -35.115, longitude: 147.3677778, displayName: 'Wagga Wagga NSW 2650' };
test('out-of-order location responses, immutability, reuse, and Finished reset', async () => {
  const waiting = []; let calls = 0;
  globalThis.fetch = (url, options) => { calls++; return new Promise(resolve => waiting.push({ resolve, body: JSON.parse(options.body) })); };
  const first = ensureBaseline(a), second = ensureBaseline(b);
  const reply = location => ({ ok: true, json: async () => ({ status: 'ready', official: true, baselineCDI: { official: true, location, rainfallIndex: 24, snapshotDate: '2026-08-31' } }) });
  waiting[1].resolve(reply(b)); await second;
  waiting[0].resolve(reply(a)); await first;
  assert.equal(appSession.get().baseline.baselineCDI.location.displayName, b.displayName);
  assert.throws(() => { appSession.get().baseline.baselineCDI.rainfallIndex = 90; }, TypeError);
  appSession.updateSimulation({ droughtIntensity: 'extreme', selectedStrategies: ['stubble-retention','wider-rows'], status: 'complete' });
  await ensureBaseline(b);
  assert.equal(calls, 2, 'same location reuses baseline, irrespective of scenario/farm management');
  assert.equal(appSession.get().baseline.baselineCDI.rainfallIndex,24);
  appSession.updateResults({ selectedStrategies: ['stubble', 'combined'], step: 2 });
  appSession.updateResults({ step: 1 });
  assert.deepEqual(appSession.get().results.selectedStrategies, ['stubble', 'combined']);
  appSession.finishSession();
  assert.equal(appSession.get().simulation.status, 'idle');
  assert.equal(appSession.get().simulation.output, null);
  assert.equal(appSession.get().simulationStartDate, null);
  assert.equal(appSession.get().baseline.baselineCDI, null);
  assert.equal(storage.get('farm-forward:setup:v2'),'{"paddockSizeHa":12.5,"soilType":"clay"}');
});
