import type { MoistureTransportInput } from './soilMoistureTransport';

/** Review fixtures only. Positive flux flags explicitly declare the intended
 * process; these are NOT calibrated quantities, capacities, rates or mm. */
export const MOISTURE_TRANSPORT_PRESETS = {
  redistribution: { label: 'A · Downward redistribution',
    previousMoisture: { topsoil: .80, rootZone: .40, deepSoil: .25 },
    nextMoisture: { topsoil: .55, rootZone: .55, deepSoil: .35 },
    fluxes: { topToRoot: 1, rootToDeep: 1 } },
  evaporation: { label: 'B · Surface drying / evaporation',
    previousMoisture: { topsoil: .70, rootZone: .55, deepSoil: .60 },
    nextMoisture: { topsoil: .25, rootZone: .48, deepSoil: .58 },
    fluxes: { evaporationLoss: 1 } },
  infiltration: { label: 'C · Wetting / infiltration',
    previousMoisture: { topsoil: .20, rootZone: .30, deepSoil: .40 },
    nextMoisture: { topsoil: .75, rootZone: .55, deepSoil: .45 },
    fluxes: { rainfallInput: 1, topToRoot: 1, rootToDeep: 1 } },
  deepStorage: { label: 'D · Deep storage',
    previousMoisture: { topsoil: .45, rootZone: .55, deepSoil: .40 },
    nextMoisture: { topsoil: .35, rootZone: .45, deepSoil: .65 },
    fluxes: { rootToDeep: 1 } },
  destination: { label: 'E · Destination check 15 / 45 / 75',
    previousMoisture: { topsoil: .70, rootZone: .30, deepSoil: .40 },
    nextMoisture: { topsoil: .15, rootZone: .45, deepSoil: .75 },
    fluxes: { evaporationLoss: 1, topToRoot: 1, rootToDeep: 1 } },
  upward: { label: 'F · Upward internal redistribution',
    previousMoisture: { topsoil: .25, rootZone: .40, deepSoil: .80 },
    nextMoisture: { topsoil: .40, rootZone: .55, deepSoil: .55 },
    fluxes: { deepToRoot: 1, rootToTop: 1 } },
  topToRoot: { label: 'G · Topsoil → Root Zone only',
    previousMoisture: { topsoil: .80, rootZone: .30, deepSoil: .45 },
    nextMoisture: { topsoil: .55, rootZone: .55, deepSoil: .45 },
    fluxes: { topToRoot: 1 } },
  rootToDeep: { label: 'H · Root Zone → Deep Soil only',
    previousMoisture: { topsoil: .45, rootZone: .80, deepSoil: .30 },
    nextMoisture: { topsoil: .45, rootZone: .55, deepSoil: .55 },
    fluxes: { rootToDeep: 1 } },
  deepToRoot: { label: 'I · Deep Soil → Root Zone only',
    previousMoisture: { topsoil: .45, rootZone: .30, deepSoil: .80 },
    nextMoisture: { topsoil: .45, rootZone: .55, deepSoil: .55 },
    fluxes: { deepToRoot: 1 } },
  rootToTop: { label: 'J · Root Zone → Topsoil only',
    previousMoisture: { topsoil: .30, rootZone: .80, deepSoil: .45 },
    nextMoisture: { topsoil: .55, rootZone: .55, deepSoil: .45 },
    fluxes: { rootToTop: 1 } },
  neutral: { label: 'K · Neutral layer changes · no causal flux',
    previousMoisture: { topsoil: .70, rootZone: .30, deepSoil: .40 },
    nextMoisture: { topsoil: .25, rootZone: .30, deepSoil: .70 }, fluxes: {} },
  drainage: { label: 'L · Supplied bottom drainage · debug only',
    previousMoisture: { topsoil: .45, rootZone: .55, deepSoil: .75 },
    nextMoisture: { topsoil: .45, rootZone: .55, deepSoil: .40 },
    fluxes: { bottomDrainage: 1 } },
} satisfies Record<string, Omit<MoistureTransportInput, 'durationSeconds'> & { label: string }>;
export type MoisturePresetId = keyof typeof MOISTURE_TRANSPORT_PRESETS;
